name: ci-cd

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

env:
  DOTNET_VERSION: "8.0.x"
  API_PROJECT: "src/HotelBooking.Api/HotelBooking.Api.csproj"
  PUBLISH_DIR: "publish"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --no-restore -c Release

      - name: Test (Release)
        run: dotnet test --no-build -c Release --verbosity normal

      - name: Publish API
        if: github.ref == 'refs/heads/master'
        run: dotnet publish ${{ env.API_PROJECT }} -c Release -o ${{ env.PUBLISH_DIR }} --no-build

      - name: Upload artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api
          path: ${{ env.PUBLISH_DIR }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "hotelbookingbytarek"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIR }}
